<a href="https://colab.research.google.com/github/Matheusbcy/-Data-Science-IA-/blob/main/Deep%20Learning/Boltzmann%20Machines/Recomenda%C3%A7%C3%A3o_de_filmes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deep Learning Boltzmann Machines - Recomendação de filmes

In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
import rbm

In [ ]:
rbm = rbm.RBM(num_visible = 6,  num_hidden = 2)

In [ ]:
base = np.array([[1, 1, 1, 0, 0, 0], [1, 0, 1, 0, 0, 0], [1, 1, 1, 0, 0, 0], [0, 0, 1, 1, 1, 1], [0, 0, 1, 1, 0, 1], [0, 0, 1, 1, 0, 1]])
filmes = ["A bruxa", "Invocação do mal", "O chamado", "Se beber não case", "Gente grande", "American pie"]

In [ ]:
rbm.train(base, max_epochs=5000)

In [ ]:
rbm.weights, rbm.weights.shape

(array([[ 2.48144173,  2.41060222,  0.41437748],
        [-1.03456701, -3.216903  ,  7.93233539],
        [ 0.1786232 , -7.24442731,  3.2690372 ],
        [ 4.94213011,  3.98104622,  1.90269648],
        [ 0.94770623,  3.62921602, -8.23232722],
        [-1.31598882,  0.61098502, -4.55073866],
        [ 0.95287941,  3.62524342, -8.23487596]]),
 (7, 3))

In [ ]:
usuario1 = np.array([[1, 1, 0, 1, 0, 0]])
usuario2 = np.array([[0, 0, 0, 1, 1, 0]])

In [ ]:
rbm.run_visible(usuario1)

array([[0., 1.]])

In [ ]:
rbm.run_visible(usuario2)

array([[1., 0.]])

In [ ]:
camada_escondida = np.array([[1, 0,]])
recomendacao = rbm.run_hidden(camada_escondida)
recomendacao

array([[0., 0., 1., 1., 0., 1.]])

In [ ]:
for i in range(len(usuario1[0])):
  if usuario1[0, i] == 0 and recomendacao[0, i] == 1:
    print(filmes[i])

O chamado
American pie
